# Generated by Django 5.2.8 on 2025-11-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(default='Myanmar', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
