# Generated by Django 5.2.8 on 2025-11-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_lowest_price_hotel_star_alter_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('beds', models.PositiveIntegerField(default=1)),
                ('size', models.PositiveIntegerField(default=200, help_text='Room size in sq ft')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_types/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.PositiveBigIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('RoomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel.roomtype')),
            ],
        ),
    ]
